local gt = this.getroottable();

if (!("Strings" in gt.Const))
{
	gt.Const.Strings <- {
		function getArticle( _object )
		{
			return this.isFirstCharacter(_object, [
				"A",
				"E",
				"I",
				"O",
				"U"
			]) ? "一个" : "一个";
		}

		function getArticleCapitalized( _object )
		{
			return this.isFirstCharacter(_object, [
				"A",
				"E",
				"I",
				"O",
				"U"
			]) ? "一个" : "一个";
		}

	};
}

if (!("Tactical" in gt.Const.Strings))
{
	gt.Const.Strings.Tactical <- {};
}

if (!("World" in gt.Const.Strings))
{
	gt.Const.Strings.World <- {};
}

gt.Const.Strings.Quantity <- [
	"1st",
	"2nd",
	"3rd",
	"4th",
	"5th",
	"6th",
	"7th",
	"8th",
	"9th",
	"10th",
	"11th",
	"12th",
	"13th",
	"14th",
	"15th",
	"16th",
	"17th",
	"18th",
	"19th",
	"20th"
];
gt.Const.Strings.Amount <- [
	"no",
	"1",
	"2",
	"3",
	"4",
	"5",
	"6",
	"7",
	"8",
	"9",
	"10",
	"11",
	"12",
	"13",
	"14",
	"15",
	"16",
	"17",
	"18",
	"19",
	"20",
	"21",
	"22",
	"23",
	"24",
	"25",
	"26",
	"27",
	"28",
	"29",
	"30"
];
gt.Const.Strings.AmountC <- [
	"No",
	"1",
	"2",
	"3",
	"4",
	"5",
	"6",
	"7",
	"8",
	"9",
	"10",
	"11",
	"12",
	"13",
	"14",
	"15",
	"16",
	"17",
	"18",
	"19",
	"20",
	"21",
	"22",
	"23",
	"24",
	"25",
	"26",
	"27",
	"28",
	"29",
	"30"
];
gt.Const.Strings.Difficulty <- [
	"初学者",
	"老兵",
	"专家"
];
gt.Const.Strings.EntityName <- [
	"亡灵巫师",
	"丧尸",
	"武装丧尸",
	"堕落英雄",
	"复仇之魂",
	"古代辅助士兵",
	"古代军团士兵",
	"古代仪仗队",
	"古代祭司",
	"征服者",
	"吸血鬼",
	"幽灵",
	"食尸鬼",
	"兽人青年",
	"兽人狂战士",
	"兽人战士",
	"兽人军阀",
	"民兵",
	"民兵射手",
	"民兵老兵",
	"民兵队长",
	"赏金猎人",
	"农民",
	"商队帮工",
	"商队护卫",
	"大篷车",
	"步兵",
	"双手剑士",
	"镰钩兵",
	"重弩手",
	"掌旗手",
	"军士",
	"骑士",
	"驴",
	"强盗暴徒",
	"强盗偷猎者",
	"强盗神射手",
	"强盗掠夺者",
	"强盗首领",
	"哥布林伏击者",
	"哥布林散兵",
	"哥布林督军",
	"哥布林萨满",
	"哥布林狼骑",
	"狼",
	"战犬",
	"装甲战犬",
	"雇佣兵",
	"雇佣兵",
	"剑术大师",
	"野骑士",
	"大师射手",
	"绿皮投石机",
	"邪教徒",
	"恐狼",
	"林德虫",
	"巨魔",
	"巨魔",
	"巨魔",
	"织网蛛",
	"织网蛛的卵",
	"梦魔",
	"女巫",
	"树人",
	"树苗",
	"野人",
	"克拉肯",
	"鬼火触手",
	"堕落背叛者",
	"恶梦",
	"野蛮人战奴",
	"野蛮人劫掠者",
	"野蛮人神选者",
	"野蛮人鼓手",
	"野蛮人兽王",
	"装甲巨魔",
	"装甲巨魔",
	"野蛮人国王",
	"战獒",
	"伊吉洛克",
	"野蛮人疯子",
	"大蛇",
	"伊弗利特",
	"鬣狗",
	"征召兵",
	"火铳手",
	"军官",
	"工程师",
	"刺客",
	"负债者",
	"角斗士",
	"炮手",
	"游牧割喉者",
	"游牧亡命徒",
	"游牧投石手",
	"游牧弓箭手",
	"游牧领袖",
	"沙漠追猎者",
	"游牧刽子手",
	"刀锋舞者",
	"公民",
	"博学者",
	"博学者的幻影",
	"命匣",
	"失落的宝藏猎人",
	"尖啸骷髅头",
	"渡誓者"
];
gt.Const.Strings.EntityNamePlural <- [
	"亡灵巫师",
	"丧尸",
	"武装丧尸",
	"堕落英雄",
	"复仇之魂",
	"古代辅助士兵",
	"古代军团士兵",
	"古代仪仗队",
	"古代祭司",
	"征服者",
	"吸血鬼",
	"幽灵",
	"食尸鬼",
	"兽人青年",
	"兽人狂战士",
	"兽人战士",
	"兽人军阀",
	"民兵",
	"民兵射手",
	"民兵老兵",
	"民兵队长",
	"赏金猎人",
	"农民",
	"商队帮工",
	"商队护卫",
	"大篷车推车",
	"步兵",
	"双手剑士",
	"镰钩兵",
	"重弩手",
	"掌旗手",
	"军士",
	"骑士",
	"驴",
	"强盗暴徒",
	"强盗偷猎者",
	"强盗神射手",
	"强盗掠夺者",
	"强盗首领",
	"哥布林伏击者",
	"哥布林散兵",
	"哥布林督军",
	"哥布林萨满",
	"哥布林狼骑",
	"狼",
	"战犬",
	"装甲战犬",
	"雇佣兵",
	"雇佣兵",
	"剑术大师",
	"野骑士",
	"大师射手",
	"绿皮投石机",
	"邪教徒",
	"恐狼",
	"林德虫",
	"巨魔",
	"巨魔",
	"巨魔",
	"织网蛛",
	"织网蛛的卵",
	"梦魔",
	"女巫",
	"树人",
	"树苗",
	"野人",
	"克拉肯",
	"鬼火触手",
	"堕落背叛者",
	"恶梦",
	"野蛮人战奴",
	"野蛮人劫掠者",
	"野蛮人神选者",
	"野蛮人鼓手",
	"野蛮人兽王",
	"装甲巨魔",
	"装甲巨魔",
	"野蛮人国王",
	"战獒",
	"冬之野兽",
	"野蛮人疯子",
	"大蛇",
	"伊弗利特",
	"鬣狗",
	"征召兵",
	"火铳手",
	"军官",
	"工程师",
	"刺客",
	"负债者",
	"角斗士",
	"迫击炮",
	"游牧割喉者",
	"游牧亡命徒",
	"游牧投石手",
	"游牧弓箭手",
	"游牧领袖",
	"沙漠追猎者",
	"游牧刽子手",
	"刀锋舞者",
	"公民",
	"博学者",
	"博学者的幻影",
	"命匣",
	"失落的宝藏猎人",
	"尖啸骷髅头",
	"渡誓者"
];
gt.Const.Strings.Tactical.EntityName <- {
	Boulder = "大石头",
	Ruin = "废墟",
	Shrubbery = "灌木丛",
	Tree = "树",
	Brush = "灌木丛",
	Cartwheel = "旧车轮",
	RuinedPillar = "毁坏的柱子",
	Cart = "商队货车",
	Donkey = "驴",
	Plant = "植物"
};
gt.Const.Strings.Tactical.EntityDescription <- {
	Boulder = "一块大石头，阻挡了移动和视野。",
	Ruin = "早已逝去的时代遗留下来的废墟。",
	Shrubbery = "非常茂密的灌木丛，阻挡了移动和视野。",
	Tree = "一棵有着巨大树干的大树。",
	TreeSwamp = "这棵树已经腐烂并早就死去。",
	TreeTrunk = "一段一半淹没在脏水中的树干。",
	Brush = "非常茂密的灌木丛，阻挡了移动和视野。",
	Cartwheel = "一辆牛车的破旧车轮。",
	RuinedPillar = "TODO",
	Cart = "一辆满载贸易商品的货车。",
	Donkey = "用来拉重车的驴。",
	Plant = "一种异域风情的植物，阻挡了移动和视野。"
};
gt.Const.Strings.FootprintsType <- [
	"",
	"北方士兵",
	"南方士兵",
	"大篷车",
	"农民",
	"民兵",
	"难民",
	"强盗",
	"亡灵",
	"兽人",
	"哥布林",
	"野蛮人",
	"游牧民",
	"恐狼",
	"食尸鬼",
	"鬣狗",
	"大蛇",
	"织网蛛",
	"巨魔",
	"梦魔",
	"女巫",
	"树人",
	"克拉肯",
	"伊弗利特",
	"林德虫",
	"雇佣兵"
];
gt.Const.Strings.ShipNames <- [
	"夏日阳光(Summer Daze)",
	"快乐的雾(Merry Mist)",
	"海啸(Howl of the Sea)",
	"珊瑚秘密(Coral Secret)",
	"桑迪湾(Sandy Bay)",
	"海之夫人(Lady of the Sea)",
	"接龙(Solitaire)",
	"布伦希尔德(Brunhild)",
	"玛蒂尔达(Mathilda)",
	"灾星(Comet)",
	"领主(Tetrarch)",
	"洛峡湾(Lofjord)",
	"秋风(Autumn Wind)",
	"庞德梅克(Poundmaker)",
	"刹车(Brakel)",
	"七颗星(Seven Stars)",
	"黑暗预兆(Dark Omen)",
	"和睦(Concord)",
	"信天翁(Albatros)",
	"金马(Golden Horse)",
	"海若虫(Sea Nymph)",
	"曲折的命运(Twisted Fate)",
	"国王的赏金(King's Bounty)",
	"秃僧(Bald Monk)",
	"金太阳(Golden Sun)",
	"虚荣(Vanity)",
	"布拉森(Brazen)",
	"虎爪(Tiger's Claw)",
	"梧桐(Sycamore)",
	"贵族赛跑者(Noble Runner)",
	"黯淡的月亮(Bleak Moon)",
	"族人(Clansman)",
	"鲸鱼之旅(Whale's Voyage)",
	"快速匹配(Quickmatch)",
	"蚋(Blackfly)",
	"埃纳尔埃里克森(Ejnar Erikson)",
	"林德虫",
	"最高(Supreme)",
	"格里芬(Griffon)",
	"阿克斯福德(Axford)",
	"伯莎(Bertha)",
	"海鸥(Seagull)",
	"别西卜(Belzebub)"
];
gt.Const.Strings.MercenaryCompanyNames <- [
	"Iron Ravens",
	"Golden Order",
	"Swords of the South",
	"Wolves of Bleak Forest",
	"Black Shields",
	"Iron Crown Company",
	"Radobrecht\'s Swords",
	"Whistling Arrows",
	"Azure Boars",
	"Fang and Coin",
	"Red Legion",
	"Hungry Hounds",
	"Crimson Daggers",
	"King\'s End Company",
	"Black Company",
	"Second Sons",
	"Walther\'s Fellowship",
	"Grudgebringers",
	"Bernhard\'s Bears",
	"Silver Claw",
	"Iron Brotherhood",
	"Orcbane Company",
	"Iron Covenant",
	"Unbroken Third",
	"Dogs of War",
	"Falkenberg\'s Legion",
	"Free Men",
	"Lords of War",
	"Northern Company",
	"Forsaken Returned",
	"White Company",
	"Widowmakers",
	"Cold Hearts Company",
	"Burning Sun Company",
	"Chosen Few",
	"Dead Men",
	"Bronzeheads",
	"Markland Pikes",
	"Hammerguard",
	"Crowntakers",
	"Silverreach Spears",
	"Iron Pact",
	"Blood Bound",
	"Bulwark",
	"Dawn\'s March",
	"Sons of Winter",
	"Company of the River House",
	"Flaming Comet Company",
	"Grand Company",
	"Rightful Ravagers",
	"Forsaken Brigade",
	"Battle\'s Chosen",
	"Bringers of Peace",
	"Shields of the Night",
	"Mongrels",
	"Bone Wardens",
	"Lost Legion"
];
gt.Const.Strings.NobleHouseNames <- [
	"格林蒙德(Grimmund)",
	"威尔堡(Weilburg)",
	"阿姆斯贝格(Armsberg)",
	"哥达(Gota)",
	"埃森斯坦(Eisenstein)",
	"格劳沃尔(Grauwall)",
	"拉本霍尔特(Rabenholt)",
	"萨默温(Sommerwein)",
	"温特霍尔(Winterhall)",
	"鲁姆特(Ruhmolt)",
	"阿德尔赖希(Adelreich)",
	"佩罗温格(Perowinger)",
	"伊格洛夫(Eiglof)",
	"贝伦加尔(Berengar)",
	"冈巴尔德(Gunbald)",
	"高斯温(Goswin)",
	"阿德尔海姆(Adelheim)",
	"阿蒙德(Ammondt)",
	"巴托林(Bartholin)",
	"埃伯林(Eberlin)",
	"福尔萨赫(Folsach)",
	"赫定(Hedin)",
	"霍恩(Horn)",
	"尼德加德(Niedergard)",
	"罗森文(Rosenving)",
	"图拉(Thurah)",
	"卡尔滕伯恩(Kaltenborn)",
	"克里格(Krieger)",
	"斯坦沃尔(Steinwall)",
	"哈康(Harkon)",
	"奥斯滕(Osten)"
];
gt.Const.Strings.CityStateNames <- [
	"Dahab",
	"Kabira",
	"Ras Sanan",
	"Tanwir",
	"Azim Shab",
	"Tarwa",
	"Hakim Al Ramal",
	"Karrakan",
	"Al-Hazred",
	"Al-Hazif",
	"Quadim",
	"Hikma",
	"El-Hadet",
	"Al-Anwar"
];
gt.Const.Strings.CityStateTitles <- [
	"城邦",
	"城市",
	"摄政市",
	"王国",
	"都市",
	"自由城",
	"圣城"
];
gt.Const.Strings.BusinessReputation <- [
	"奸诈的",
	"无能的",
	"不可靠的",
	"无名的",
	"认可的",
	"可靠的",
	"胜任的",
	"专业的",
	"信誉良好的",
	"著名的",
	"伟大的",
	"辉煌的",
	"传说中的",
	"传奇的",
	"无敌的",
	"不朽的"
];
gt.Const.Strings.MoralReputation <- [
	"可怖",
	"残忍",
	"无情",
	"恶劣",
	"中立",
	"中立",
	"和善",
	"善良",
	"侠义",
	"圣人"
];
gt.Const.Strings.Relations <- [
	"敌对",
	"受威胁",
	"不友好",
	"冷淡",
	"中立",
	"中立",
	"热情",
	"友好",
	"很友好",
	"盟友"
];
gt.Const.Strings.Tactical.TerrainName <- [
	"全无",
	"泥路",
	"粘土路",
	"鹅卵石路",
	"草原",
	"污垢",
	"森林",
	"泥泞的地面",
	"潮湿的草地",
	"浑浊的水",
	"草原",
	"干草原",
	"苔原",
	"雪",
	"小雪",
	"石地",
	"石地",
	"沙",
	"浅水"
];
gt.Const.Strings.Tactical.TerrainDescription <- [
	"全无",
	"人类和动物不断压过形成的土路。",
	"一条由夯实粘土组成的原始道路。",
	"用于马车和大型车辆的鹅卵石道路。",
	"结实平坦覆盖着短草的地面。",
	"裸露而平坦的土地，几乎没有任何植被。",
	"覆盖着一层又厚又软的苔藓的森林地面。",
	"泥泞发黑的土地。",
	"总体上结实且覆盖着长而柔软的杂草的地面。",
	"浑浊的浅水覆盖着的泥地。",
	"干枯的草覆盖着的平坦坚实的地面。",
	"被太阳的热量完全干燥的坚硬土地。",
	"杂草覆盖的平坦而干旱的地面。",
	"被厚厚雪层所覆盖的冰冻的地面。",
	"被一层薄雪覆盖的冰冻的地面。",
	"便于立足的光滑石头地面。",
	"粗糙的石头地面。",
	"灼热的沙漠沙子。",
	"清澈而浅的水。"
];
gt.Const.Strings.UI <- {
	Introduction = "你沉浸在凉爽的早晨空气中。随着太阳慢慢升起，你生活中的新篇章也开始了。经过多年为微薄的薪水而血腥杀戮，你已经攒够了足够的钱来创办自己的雇佣兵公司。和你在一起的是%allbrothers%，你曾在盾墙中并肩作战。你现在是他们的指挥官，%companyname% 的领导者。\n\n当你在这片土地上旅行时，你应该在村庄和城市雇佣新的人来填补你的队伍。许多提供服务的人以前从未拿起过真正的武器。也许他们绝望了，也许他们贪婪地快速获得战利品。他们中的大多数会死在战场上。但不要气馁。这就是佣兵的生活，下一个村庄总会有新人热切地寻找新的生活开始。\n\n现在的土地很危险。强盗和掠夺者埋伏在路边，野兽在黑暗的森林中游荡，兽人部落在东部的沼泽中躁动不安。甚至有传言说黑魔法在起作用，死者从坟墓中复活并再次行走。有很多赚钱的机会，无论是通过在全国各地的村庄、城市和要塞中找到的合同，还是通过自己冒险去探索和袭击。\n\n你的手下期待着你下达命令。他们现在为 %companyname% 生死存亡。\n\n[color=#bd9d71]早期访问免责声明：此版本仍在大量工作中，并不代表产品的最终质量。功能可能不完整或缺失，UI 尚未剥皮，会有错误，经济、资源和敌人的平衡和进展可能需要调整，有时可能太具有挑战性或太容易。抢先体验期间将添加许多额外内容，包括更多敌人、物品、合同、地形类型、独特位置、故事事件和其他功能。[/color]",
	FleeDialogueConsequences = "有时最好进行一次战术撤退以便活着见到明天的太阳。你的手下将尝试自己到达地图的边缘然后安全撤退。然而敌人可能会追上来，目前已经接敌的人恐怕无法安然无恙的撤出来。",
	RetreatDialogueConsequences = "敌人被收拾的满地找牙。那些少数幸存的家伙向四面八方散去。你要追捕他们以夺取他们的头颅和财物，还是宣布战斗胜利？"
};
gt.Const.Strings.AlpStateName <- [
	"",
	"部分存在于梦中",
	"部分存在于梦中",
	"主要存在于梦中",
	"主要存在于梦中"
];
gt.Const.Strings.BodyPartName <- [
	"身体",
	"头部"
];
gt.Const.Strings.ItemSlotName <- [
	"身体",
	"头部",
	"主手",
	"副手",
	"配饰",
	"背包"
];
gt.Const.Strings.World.TimeOfDay <- [
	"黎明",
	"早晨",
	"正午",
	"下午",
	"傍晚",
	"黄昏",
	"夜晚",
	"黎明"
];
gt.Const.Strings.Direction <- [
	"[color=#ffff00]北方[/color]",
	"[color=#ffff00]东北方[/color]",
	"[color=#ffff00]东南方[/color]",
	"[color=#ffff00]南方[/color]",
	"[color=#ffff00]西南方[/color]",
	"[color=#ffff00]西北方[/color]",
	"<未定义>"
];
gt.Const.Strings.Direction8 <- [
	"[color=#ffff00]北方[/color]",
	"[color=#ffff00]东北方[/color]",
	"[color=#ffff00]东方[/color]",
	"[color=#ffff00]东南方[/color]",
	"[color=#ffff00]南方[/color]",
	"[color=#ffff00]西南方[/color]",
	"[color=#ffff00]西方[/color]",
	"[color=#ffff00]西北方[/color]"
];
gt.Const.Strings.Terrain <- [
	"",
	"[color=#ff0000]海洋里[/color]",
	"[color=#ff0000]平原上[/color]",
	"[color=#ff0000]沼泽里[/color]",
	"[color=#ff0000]小山上[/color]",
	"[color=#ff0000]森林里[/color]",
	"[color=#ff0000]森林里[/color]",
	"[color=#ff0000]森林里[/color]",
	"[color=#ff0000]森林里[/color]",
	"[color=#ff0000]山脊间[/color]",
	"",
	"",
	"[color=#ff0000]雪地里[/color]",
	"[color=#ff0000]荒原里[/color]",
	"[color=#ff0000]苔原里[/color]",
	"[color=#ff0000]草原里[/color]",
	"[color=#ff0000]在岸边[/color]",
	"[color=#ff0000]沙漠里[/color]",
	"[color=#ff0000]湿地里[/color]"
];
gt.Const.Strings.TerrainAlternative <- [
	"",
	"",
	"[color=#ff0000]平原上[/color]",
	"[color=#ff0000]沼泽里[/color]",
	"[color=#ff0000]小山上[/color]",
	"[color=#ff0000]森林里[/color]",
	"[color=#ff0000]森林里[/color]",
	"[color=#ff0000]森林里[/color]",
	"[color=#ff0000]森林里[/color]",
	"[color=#ff0000]山脊间[/color]",
	"[color=#ff0000]平原上[/color]",
	"[color=#ff0000]平原上[/color]",
	"[color=#ff0000]雪地里[/color]",
	"",
	"[color=#ff0000]苔原里[/color]",
	"[color=#ff0000]草原里[/color]",
	"",
	"[color=#ff0000]沙漠里[/color]",
	"[color=#ff0000]湿地里[/color]"
];
gt.Const.Strings.TerrainShort <- [
	"",
	"[color=#ff0000]海湾[/color]",
	"[color=#ff0000]平原[/color]",
	"[color=#ff0000]沼泽[/color]",
	"[color=#ff0000]山丘[/color]",
	"[color=#ff0000]森林[/color]",
	"[color=#ff0000]森林[/color]",
	"[color=#ff0000]森林[/color]",
	"[color=#ff0000]森林[/color]",
	"[color=#ff0000]高山[/color]",
	"",
	"",
	"[color=#ff0000]雪地[/color]",
	"[color=#ff0000]荒原[/color]",
	"[color=#ff0000]苔原[/color]",
	"[color=#ff0000]草原[/color]",
	"[color=#ff0000]水岸[/color]",
	"",
	"[color=#ff0000]沙漠[/color]",
	"[color=#ff0000]山丘[/color]",
	"[color=#ff0000]湿地[/color]"
];
gt.Const.Strings.TerrainRegionNames <- [
	[],
	[
		"Stormy Sea",
		"Kraken\'s Refuge",
		"White Horses Sea",
		"Thousand Gulls Sea",
		"Deep Depths",
		"Rainy Ocean",
		"Unbound Ocean",
		"Tempest Ocean",
		"Thunder Sea",
		"Great Sea",
		"Surging Sea",
		"Pearl Sea",
		"Howling Sea",
		"Cruel Sea",
		"Arching Tides Ocean",
		"Whispering Waves Sea",
		"Soft Ripple Sea",
		"Green Sea",
		"Sea of Turning Tides",
		"Wailing Ocean",
		"Foamy Shallows",
		"Murky Tide Ocean",
		"Shimmering Expanse",
		"Azure Expanse",
		"The Raging Gulf",
		"The Shimmering Depths"
	],
	[
		"Vendland",
		"Speedwell Fields",
		"Plainshire",
		"Vinland",
		"Lowlands",
		"Windlands",
		"Wide Watch",
		"Glaucious Domain",
		"Rich Meadows",
		"Markland",
		"Fast Clouds County",
		"Fairdale",
		"Fleetfeet\'s Range",
		"Wanderer\'s Boon",
		"Valeshire",
		"Ridland",
		"Greenfold",
		"Hogfolk",
		"Durum",
		"Shallowford",
		"Two Fields",
		"Kingmill",
		"Minceacre",
		"Glendale",
		"Brillfold",
		"Kindon",
		"Greenmere",
		"Mooseridge",
		"Altmark",
		"Neumark",
		"Fair Range",
		"Middlemark",
		"Grasslands",
		"Moss Valley",
		"Wideacre",
		"Southbloom",
		"Dawnland",
		"Oak Wood Meadows",
		"Southwind Acres",
		"Meadowcove",
		"Willow\'s Fields",
		"Grand View Pastures",
		"Nightingale Valley",
		"Silversage Fields",
		"Heartsong\'s Range"
	],
	[
		"Black Marshes",
		"Dead Ponds",
		"Tar Fields",
		"Peatfold",
		"Suffocating Bog",
		"Eerie Marshes",
		"Black Morass",
		"Sticky Wallow",
		"Dreaded Mire",
		"Murky Swamplands",
		"Mortun",
		"Blackfan",
		"Gallowsbog",
		"Dungslump",
		"Houndsmarsh",
		"Shipreath Marsh",
		"Cursed Lands",
		"Grimdowns",
		"The Reeds",
		"Froghold",
		"Spidergrove",
		"Duke\'s Demise",
		"Bottomless Pits",
		"Poisonbreath Marshes",
		"Froglickers Grove",
		"Deadbottom",
		"The Wetlands",
		"The Marshlands",
		"Black Mud",
		"Desolate Moor",
		"Black Fumes Polder",
		"Endless Polder",
		"Peat Basin",
		"Riverland Glades",
		"Southland Bowels",
		"Azure Marsh",
		"Thousand Mirrors Bog",
		"The Narrow Quag",
		"Glades of Decay",
		"Ashen Wetlands",
		"Savage Bog",
		"Mire of the Whisp",
		"Forbidden Waters",
		"Dreadmoor"
	],
	[
		"Bonefold Barrow",
		"Knight\'s Axe Hills",
		"Skullsbreath Mound",
		"Ancient Knolls",
		"Oldlock Hills",
		"The Hummocks",
		"Knowesfold",
		"Ancient Cairns",
		"Humming Hills",
		"Sharp Rocks",
		"Misty Barrows",
		"Boulderhills",
		"Scree Barrows",
		"Bed Load Knolls",
		"Ghost Hills",
		"Banshee Mounds",
		"Shinglehumps",
		"Earthwatch Hills",
		"Giant\'s Pebbles",
		"Buried Snake Hills",
		"Skullslide Hills",
		"Rustcave Hills",
		"Witchmount Hills",
		"Juniper Hills",
		"White Goat Mounds",
		"Barum",
		"The Reach",
		"Whispering Hills",
		"The Bronze Hills",
		"Willowshire Hillside",
		"The Scarlet Hills",
		"Giant\'s Slopes",
		"The Gloomy Hills",
		"The Collapsing Hills"
	],
	[
		"Bleak Forest",
		"Dire Woods",
		"Dismal Woods",
		"Dusky Forest",
		"Scoundrels\' Forest",
		"Boar Woods",
		"Bandit\'s Rest",
		"Splinterdale",
		"Spiderwood",
		"Tickbrake",
		"Druid\'s Grove",
		"Brittle Branch Woods",
		"White Wolf\'s Home",
		"Ravenhold",
		"Needlegrove",
		"Rustling Thicket",
		"Mossy Pine Woods",
		"Crows Nest",
		"Black Forest",
		"Prowlers Woods",
		"Gloomy Woods",
		"Wolfwood",
		"Black Woods",
		"Murmuring Woods",
		"Dark Thorn Wilds",
		"Hedgehog Thicket",
		"Misty Covert",
		"Borderdale",
		"Temple Grove",
		"Wretched Woods",
		"Elder Woods",
		"Deep Covert",
		"Macaw Woods",
		"Hexenwald"
	],
	[],
	[
		"Ancient Forest",
		"Ranger\'s Rest",
		"Valley of the Deer",
		"Oldgrowth",
		"Rampants",
		"Ironoak Grove",
		"Hunter\'s Bosk",
		"Royal Grounds",
		"Sylvan Woods",
		"Fox and Hare Woods",
		"Snapping Twig Forest",
		"Antlerfold",
		"Old Forest",
		"Greenwood Forest",
		"Mossy Woods",
		"Misty Woods",
		"The Sea of Trees",
		"Timberland",
		"Whispering Groves",
		"Grand Hare Woods",
		"Chestnut Grove",
		"Snake\'s Covert",
		"Blackwood Forest",
		"Stormy Woods",
		"Rustling Thicket",
		"Wicked Woods",
		"Gray Toad Woodlands",
		"Treewalker Woodlands",
		"Jagged Woods",
		"Stag\'s Grounds",
		"Crowned Oak Forest",
		"Elderberry Woods",
		"Elm Grove",
		"Black Mole Woods",
		"Brookwood",
		"Springwood",
		"Everwoods"
	],
	[
		"Red Worm Woods",
		"Fiery Woods",
		"Smoldering Woods",
		"Ember Forest",
		"Vibrant Grove",
		"Foxfold Forest",
		"Somerhurst",
		"Fireander",
		"Bloodcut Growth",
		"Burnend",
		"Rustdroop",
		"Blood Woods",
		"Blazing Forest",
		"Vermillion Woods",
		"Crimson Forest",
		"Auburn Woods",
		"Redwood",
		"Badger\'s Covert",
		"Birch Timberland",
		"Waterwood Forest",
		"Pyrewood",
		"Beatroot Wilds",
		"Bogwood Grove",
		"Yellowleaf\'s Range",
		"Bloodbloom Woods",
		"Redbark Forest",
		"Firerock Grove"
	],
	[
		"Spine of the World",
		"Sleeping Giants Back",
		"Jagged Spires",
		"Wall of the Gods",
		"Dreaded Rocks",
		"Rocky Ridge",
		"Jagged Summit",
		"Silver Ridge",
		"Misty Summit",
		"Iron Mountains",
		"Goathorns",
		"Dragonteeth",
		"Highrise",
		"Eagleflight",
		"Grimroof",
		"Dunspike",
		"Dreadhorn",
		"Ravensbeak",
		"Mount Bulkhead",
		"Bulwark",
		"Cloddheads",
		"Browslopes",
		"Hero\'s Fall",
		"Yawning Gaps",
		"Mammothshoulders",
		"Swellpike Heights",
		"Bald Crown",
		"Cloudcrest",
		"Evermist Mountains",
		"Slaughtermount",
		"The Rift",
		"The Thundering Peaks",
		"Decayed Heights",
		"The Glistening Heights",
		"Deserted Rise",
		"The Vast Rise",
		"Moonlit Peaks",
		"The Ashen Pinnacle",
		"The Bare Peaks",
		"The Shadow Mountains",
		"Grimestone Peaks",
		"Brimstone Shoulders",
		"Iron Peaks"
	],
	[],
	[],
	[
		"White Waste",
		"Frozen Plains",
		"Sea of Snow",
		"White Wilderness",
		"Silver Plains",
		"Howling Wastes",
		"Silver Flats",
		"Everwinter",
		"Frozen North",
		"World\'s Rim",
		"Coldend",
		"Wintermore",
		"Icemark",
		"Spikewind",
		"Iceblade Dale",
		"Silversand Hold",
		"Frostfold",
		"Icehenge",
		"Frozen Burrows",
		"Aurora Flats",
		"Frostfinger\'s Realm",
		"Nevermelting Hold",
		"The Pale Expanse",
		"Desert of Mirrors",
		"The Ghostly Plains",
		"Chillwind Flatlands",
		"The Glazed Valley",
		"The Howling Desert",
		"The Powder Plains",
		"Snowbank"
	],
	[],
	[
		"Northmark",
		"Tablelands",
		"Scragglands",
		"Norshire",
		"Barescrub",
		"Forefathers\' Highlands",
		"Skyreach",
		"Clan\'s Claim",
		"Rugged Flats",
		"Northern Clanlands",
		"Northern Reaches",
		"Ragwilds",
		"Barrens",
		"Ragnar\'s Range",
		"Pagan Heathland",
		"Ruffmuir",
		"Windlands",
		"Angbride",
		"Baleford",
		"Bleakwolds",
		"Nordlands",
		"Glenmore Barrows",
		"Woldwich",
		"Kinmere",
		"Northurst",
		"Norenford",
		"Holmburn",
		"The Dreary Barrens"
	],
	[
		"Scrublands",
		"Drylands",
		"Torched Plains",
		"Red Lowlands",
		"Scorching Shire",
		"Golden Valley",
		"Southern Steppe",
		"Southmark",
		"The Scald",
		"Bleached Bone Dale",
		"Droughtshire",
		"Sunpan",
		"The Dryweeds",
		"Thornvale",
		"Bronze Flats",
		"Dire Hold",
		"Parcheim",
		"Smallriver Hold",
		"Razorshrub",
		"Gnarlheim",
		"Gritstone",
		"Suderos",
		"Suderland",
		"Solsweald",
		"Rustyblade Mesa",
		"Muskena",
		"Solstein",
		"Southwatch",
		"Sunreach",
		"Sandshear",
		"Skauna",
		"Caskain",
		"Maraman",
		"Jundland",
		"The Borderlands"
	],
	[],
	[
		"Silver Sands",
		"Dead Sands",
		"Golden Flats",
		"Timeless Sands",
		"Glittering Sands",
		"Scorching Desert",
		"The Emptiness",
		"The Burning Barrens",
		"Southern Sands",
		"Dusty Desert",
		"Sea of Sand",
		"Land of the Sun",
		"The Great Desert",
		"Neverending Sands",
		"Southern Reach",
		"Mumbling Sands",
		"Whispering Sands",
		"Shifting Sands",
		"Moaning Sands",
		"Sparkling Sands",
		"Glistening Flats",
		"Dry Wastes"
	],
	[
		"The Lost Oasis",
		"Green Shallows",
		"Emerald Bassin",
		"Pearl of the South",
		"Fruitful Shallows",
		"Springs of Life",
		"Gift of God",
		"Prophet\'s Salvation",
		"The Wetlands"
	]
];
gt.Const.Strings.Distance <- [
	"[color=#00ff00]较近的[/color]",
	"[color=#00ff00]不远的[/color]",
	"[color=#00ff00]稍远的[/color]",
	"[color=#00ff00]较远的[/color]",
	"[color=#00ff00]很远的[/color]",
	"[color=#00ff00]非常远的[/color]"
];
gt.Const.Strings.PartyStrength <- [
	"脆弱的",
	"弱小的",
	"平均的",
	"强大的",
	"危险的",
	"致命的",
	"无敌的"
];
gt.Const.Strings.EngageEnemyNumbers <- [
	"几个",
	"一些",
	"许多",
	"很多",
	"大量"
];
gt.Const.Strings.InventoryHeader <- [
	"驴",
	"马车",
	"货车",
	"大货车"
];
gt.Const.Strings.InventoryUpgradeHeader <- [
	"买一辆马车",
	"买一辆货车",
	"买一辆大货车"
];
gt.Const.Strings.InventoryUpgradeText <- [
	"买一辆马车",
	"买一辆货车",
	"买一辆大货车"
];
gt.Const.Strings.InventoryUpgradeCosts <- [
	"5,000",
	"10,000",
	"20,000"
];
gt.Const.Strings.PerkName <- {
	Bullseye = "神射",
	Ballistics = "弹道学",
	Berserk = "狂暴",
	DevastatingStrikes = "毁灭打击",
	KillingFrenzy = "杀戮狂潮",
	ShieldBash = "盾击",
	Brawny = "强健",
	Stalwart = "坚实",
	Taunt = "嘲讽",
	Steadfast = "坚定不移",
	Colossus = "巨像",
	ShieldExpert = "盾牌专家",
	NineLives = "九命猫",
	BatteringRam = "攻城锤",
	BattleForged = "战斗锻造",
	BagsAndBelts = "包和腰带",
	Student = "学生",
	Zweihander = "双手剑士",
	Pathfinder = "寻路者",
	FortifiedMind = "强化意志",
	Captain = "军士",
	InspiringPresence = "鼓舞人心的存在",
	QuickHands = "快手",
	CripplingStrikes = "致残打击",
	Duelist = "决斗者",
	Nimble = "轻灵",
	Dodge = "闪避",
	HoldOut = "韧性",
	Anticipation = "预判",
	SteelBrow = "钢头",
	CoupDeGrace = "处决者",
	Weaponmaster = "武器大师",
	FastAdaption = "快速适应",
	SunderingStrikes = "崩裂打击",
	BattleFlow = "战斗自如",
	HeadHunter = "猎头者",
	RallyTheTroops = "集结部队",
	Fearsome = "恐惧",
	Indomitable = "不屈不挠",
	Debilitate = "衰弱",
	Footwork = "步法",
	Rotation = "轮换",
	Underdog = "落单狗",
	Recover = "大喘气",
	Gifted = "天赋",
	Adrenaline = "肾上腺素",
	Backstabber = "背刺者",
	LoneWolf = "独狼",
	ReachAdvantage = "距离优势",
	Overwhelm = "压制",
	Relentless = "不懈",
	SpecBow = "弓精通",
	SpecCrossbow = "弩与火器精通",
	SpecThrowing = "投掷精通",
	SpecAxe = "斧精通",
	SpecCleaver = "砍刀精通",
	SpecDagger = "匕首精通",
	SpecSword = "剑精通",
	SpecSpear = "矛精通",
	SpecPolearm = "长柄精通",
	SpecHammer = "锤精通",
	SpecMace = "棍棒精通",
	SpecFlail = "链枷精通"
};
gt.Const.Strings.PerkDescription <- {
	Relentless = "不要慢下来！在任意时刻，你的主动性都只降低累积疲劳值的[color=" + this.Const.UI.Color.NegativeValue + "]50%[/color]，而不是通常的全部。此外，使用‘等待’命令将不再使你在下一回合的主动性受到惩罚。",
	Rotation = "解锁‘轮换’技能，使两个角色可以无视控制区域交换位置，前提是两个角色均未被击晕、定身或以其他方式失能。",
	Footwork = "解锁‘步法’技能，使你可以利用技巧性的步法离开敌对控制区域且不触发借机攻击。",
	Debilitate = "解锁 '衰弱' 技能，该技能可以使你的下一次攻击使目标瘫痪一回合，使其造成伤害的能力降低[color=" + this.Const.UI.Color.NegativeValue + "]-50%[/color].",
	Indomitable = "解锁‘不屈不挠’技能，可在下一个轮次开始前提供[color=" + this.Const.UI.Color.PositiveValue + "]50%[/color]的伤害减免，以及对被击晕、击退和抓取的免疫。",
	RallyTheTroops = "解锁‘集结’技能，可以集结逃跑的盟友并将附近所有盟友的士气最高提升至稳定等级。使用该技能的角色决心越高，成功的几率就越高。",
	Adrenaline = "解锁‘肾上腺素’技能，让你在下一回合的轮次中处于首位，在你的敌人之前再行动一轮。感受肾上腺素在血管中的奔涌吧！",
	Fearsome = "让他们四散而逃！任何至少造成1点生命值伤害的攻击都会触发对手的士气检定，并且惩罚等于你决心的[color=" + this.Const.UI.Color.NegativeValue + "]20%[/color] - 10，而不是仅在造成不低于15点生命值伤害时进行无惩罚检定。",
	HeadHunter = "取汝首级！击中目标的头部将使您在下一次攻击时也能保证击中头部。如果你后续的攻击命中了，这个效果会重置。",
	SunderingStrikes = "使用任意武器时的破甲效率均增加[color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color]。",
	FastAdaption = "适应你的对手的动作！每次攻击未命中时均可获得[color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color]命中率加成，可叠加但加成会在攻击命中后重置。",
	Weaponmaster = "所有的攻击的疲劳消耗减少[color=" + this.Const.UI.Color.NegativeValue + "]-20%[/color]，并且武器损坏速度减半。用你的武器优雅地跳舞，让每一击都算数。",
	CoupDeGrace = "对受到伤势(如断臂)的目标造成额外[color=" + this.Const.UI.Color.PositiveValue + "]20%[/color]伤害。",
	SteelBrow = "被击中头部不再对这个角色造成额外伤害，这也显著降低了头部遭受严重伤势的风险。",
	Anticipation = "当被远程武器攻击时，与攻击者的每格距离都提供[color=" + this.Const.UI.Color.PositiveValue + "]1 + 10%的基础远程防御[/color]作为远程防御增益，并且此增益至少为[color=" + this.Const.UI.Color.PositiveValue + "]+10[/color]。",
	HoldOut = "淡定！坚持住! 任何持续时间有限的负面状态效果(例如流血、魅惑)的持续时间都会减少到[color=" + this.Const.UI.Color.NegativeValue + "]1[/color]回合。那些效果在几个回合内逐渐减弱的状态效果(例如哥布林毒药)从一开始就处于最弱的状态。",
	Dodge = "对你来说太快了！以角色当前主动性的[color=" + this.Const.UI.Color.PositiveValue + "]15%[/color]作为近战和远程防御的额外加成。",
	Nimble = "轻甲专精！通过灵活地躲闪或偏转攻击，避免在被命中时受到直击。所受的生命值伤害最多可以减少[color=" + this.Const.UI.Color.PositiveValue + "]60%[/color]，但效果会在盔甲和头盔的最大疲劳惩罚超过[color=" + this.Const.UI.Color.PositiveValue + "]15[/color]后呈指数下降。你的盔甲和头盔越轻，你的收益就越大。\n\n‘强健’不影响此特技。\n\n不影响来自精神攻击或状态效果的伤害，但可以协助避免遭受它们。",
	BattleForged = "重甲专精！受到的护甲伤害将会以盔甲和头盔当前总护甲值总和的[color=" + this.Const.UI.Color.PositiveValue + "]5%[/color]作为百分比减少。你的盔甲和头盔越重，你的收益就越大。\n\n不影响来自精神攻击或状态效果的伤害，但可以协助避免遭受它们。",
	Duelist = "与你的武器合而为一，直击空门！如果空着副手或者携带着可投掷的工具(如投网)，则可额外造成[color=" + this.Const.UI.Color.PositiveValue + "]+25%[/color]穿甲伤害。不适用于双手武器。",
	CripplingStrikes = "致残你的敌人! 使用近战和远程攻击造成伤势的阈值均降低[color=" + this.Const.UI.Color.NegativeValue + "]33%[/color]。",
	QuickHands = "在找这个吗？在战斗中每回合第一次替换除盾牌以外的任何物品成为一个免费动作，不需要行动点数。",
	Bullseye = "射得好! 当你使用远程武器向被障碍物阻挡的目标射击时的命中惩罚从[color=" + this.Const.UI.Color.NegativeValue + "]75%[/color]减少到[color=" + this.Const.UI.Color.NegativeValue + "]50%[/color]。",
	Ballistics = "命中率的距离惩罚每格减少[color=" + this.Const.UI.Color.NegativeValue + "]-1[/color]",
	Berserk = "RAAARGH！每回合第一次击杀敌人立即恢复[color=" + this.Const.UI.Color.PositiveValue + "]4[/color]行动点数。角色恢复的行动点数不能超过其上限，一次攻击也最多只能恢复4点。",
	BattleFlow = "每回合第一次击杀对手将以基础最大疲劳的[color=" + this.Const.UI.Color.NegativeValue + "]25%[/color]降低目前积累的疲劳（基础最大疲劳不计算装备惩罚）。",
	DevastatingStrikes = "使用任意武器造成的所有伤害均增加[color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color]。现在还有什么可以拦着你？",
	KillingFrenzy = "陷入杀戮狂潮！完成一次击杀将会使所有伤害增加[color=" + this.Const.UI.Color.PositiveValue + "]25%[/color]，持续2回合。再次完成击杀不叠加，但会刷新持续时间。",
	ShieldBash = "除了通常的效果外，‘击退’技能现在还会额外造成[color=" + this.Const.UI.Color.DamageValue + "]10 ~ 25[/color]伤害(50%破甲效率)和[color=" + this.Const.UI.Color.DamageValue + "]10[/color]疲劳，并且使用技能的疲劳积累减少10。",
	Brawny = "穿戴盔甲和头盔的疲劳与主动性惩罚降低[color=" + this.Const.UI.Color.NegativeValue + "]30%[/color]。",
	Stalwart = "免疫位移技能。适用于击退，钩拽以及其他改变角色位置的技能。",
	Steadfast = "被通常攻击命中不再造成额外疲劳。专门针对疲劳的攻击不受影响。",
	Taunt = "解锁‘嘲讽’技能，使目标对手采取进攻行动而非防御行动，并且攻击使用嘲讽的角色而非其他可能更脆弱的角色。",
	Colossus = "放马过来！最大生命值提升[color=" + this.Const.UI.Color.PositiveValue + "]25%[/color]，这也降低了被击中时遭受伤势的概率。",
	ShieldExpert = "学会更好地将攻击偏转到侧面而不是正面硬挡。\n\n盾牌提供的防御加成增加[color=" + this.Const.UI.Color.PositiveValue + "]25%[/color]，这也适用于‘盾墙’技能提供的额外防御加成。\n\n盾牌受到的伤害减少[color=" + this.Const.UI.Color.NegativeValue + "]50%[/color]，但至少为1。\n\n‘击退’技能命中率提高[color=" + this.Const.UI.Color.PositiveValue + "]+15%[/color]。",
	NineLives = "每场战斗有一次机会在本来将被杀死时会幸存并残余少量生命，同时治愈所有持续造成伤害的效果(例如流血、中毒)。当然，再次被命中很可能会永久的杀死你，但在你的下一轮开始前防御属性会有所提升，从而帮助你存活到那时候。",
	BatteringRam = "免疫击晕。",
	BagsAndBelts = "解锁两个额外的背包槽位以携带所有您喜爱的物品。除了双手武器以外，放在背包里的物品不再对最大疲劳造成惩罚。",
	Student = "专心者学竟成。从战斗中获得额外[color=" + this.Const.UI.Color.PositiveValue + "]20%[/color]经验。在角色11级时，你将获得一个额外的特性点，同时此特性失效。\n\n在游玩‘搜捕者’起源时，你的负债者将在角色7级时得到返还的特性点。",
	Gifted = "当你生来就有天赋时，雇佣兵的生活会变容易。立刻得到一次升级式的属性提升，骰子均为最大值但不考虑属性天赋。",
	Zweihander = "所有双手武器技能的疲劳消耗降低 [color=" + this.Const.UI.Color.NegativeValue + "]-20%[/color].",
	Pathfinder = "学会在困难的地形上移动。在所有地形上移动的行动点消耗减少[color=" + this.Const.UI.Color.NegativeValue + "]1[/color]，最低降至每格只消耗2行动点，并且疲劳积累减半。改变高度也不再需要消耗额外的行动点。",
	FortifiedMind = "钢铁般意志不会轻易偏离正道。决心提升[color=" + this.Const.UI.Color.PositiveValue + "]25%[/color]。",
	Captain = "在战场上使用一个军士作为你领导力的延伸，并让每个人都保持斗志。5格范围内的盟友将获得该角色决心的[color=" + this.Const.UI.Color.PositiveValue + "]15%[/color]作为加成，但最大不得超过该角色的决心。\n\n效果不叠加；加成将由决心最高的军士提供。",
	InspiringPresence = "一个伟大的领袖会激励他的追随者去克服他们的极限。除非角色特性允许，否则盟友将会以自信的士气开始每场战斗。",
	Underdog = "我已经习惯了。因为被对手包围导致的防御惩罚不再适用于这个角色。如果攻击者拥有‘背刺者’特技，则该特技的效果被抵消，此时因包围导致的防御惩罚会正常应用。",
	Recover = "解锁‘大喘气’技能，使角色可以休息一回合，从而将累积的疲劳减少[color=" + this.Const.UI.Color.NegativeValue + "]50%[/color]。",
	Backstabber = "荣誉并不能让你赢得战斗，而对敌人落井下石可以。每个包围并分散目标注意力的盟友提供的近战命中增益翻倍至[color=" + this.Const.UI.Color.PositiveValue + "]10%[/color]。",
	LoneWolf = "我擅长单独行动。如果在3格范围内没有盟友，获得[color=" + this.Const.UI.Color.PositiveValue + "]15%[/color]近战技能、远程技能、近战防御、远程防御和决心的加成。",
	ReachAdvantage = "学会使用大型武器的长度优势来阻止敌人贴近到能进行有效攻击的距离。\n\n使用双手近战武器时每次命中都会叠加一层距离优势，使得近战防御增加[color=" + this.Const.UI.Color.PositiveValue + "]+5[/color]，最多可叠加5层且效果持续到此角色的下一轮。一次攻击命中多个目标可一次性叠加多层。\n\n但如果你收起你的武器，你将失去所有加成。",
	Overwhelm = "学会利用你的高主动性并且用你的攻击压制敌人，从而阻止他们进行有效的攻击！无论命中与否，对当前回合中在你之后行动的敌人进行的每次攻击都会造成‘被压制’的状态效果，使近战技能和远程技能在此回合均降低[color=" + this.Const.UI.Color.NegativeValue + "]10%[/color]。该效果会随着每次攻击叠加，并且可以一次攻击同时施加于多个目标。",
	SpecBow = "精通弓术，从远处向对手倾泻箭雨。武器技能减少[color=" + this.Const.UI.Color.NegativeValue + "]25%[/color]疲劳度积累。\n\n视野范围和使用弓时的最大射程增加[color=" + this.Const.UI.Color.PositiveValue + "]+1[/color]。",
	SpecCrossbow = "精通弩与火器，并知道瞄准何处最佳。武器技能减少[color=" + this.Const.UI.Color.NegativeValue + "]25%[/color]疲劳度积累。\n\n弩额外造成[color=" + this.Const.UI.Color.PositiveValue + "]20%[/color]穿透护甲的伤害。\n\n火铳现在仅需要[color=" + this.Const.UI.Color.NegativeValue + "]6[/color]行动点来重新装填，并且可以每回合发射，无需用间隔一回合。",
	SpecThrowing = "精通投掷武器，在敌人靠近之前就将其击伤或杀死。武器技能减少[color=" + this.Const.UI.Color.NegativeValue + "]25%[/color]疲劳度积累。\n\n当攻击距离为2格时，伤害增加[color=" + this.Const.UI.Color.PositiveValue + "]30%[/color]。\n\n当攻击距离为3格时，伤害增加[color=" + this.Const.UI.Color.PositiveValue + "]20%[/color]。",
	SpecAxe = "精通使用斧子战斗及摧毁盾牌。武器技能减少[color=" + this.Const.UI.Color.NegativeValue + "]25%[/color]疲劳度积累。\n\n使用斧子劈盾的伤害增加[color=" + this.Const.UI.Color.PositiveValue + "]50%[/color]。\n\n‘环劈’获得[color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color]命中加成。\n\n长斧攻击近身敌人不再有命中惩罚。",
	SpecCleaver = "精通使用砍刀造成可怕的伤口。武器技能减少[color=" + this.Const.UI.Color.NegativeValue + "]25%[/color]疲劳度积累。\n\n砍刀和鞭子造成的流血伤害分别增加到[color=" + this.Const.UI.Color.PositiveValue + "]10[/color]和[color=" + this.Const.UI.Color.PositiveValue + "]20[/color]每回合。\n\n‘缴械’的命中惩罚减半。",
	SpecDagger = "精通迅捷而致命的匕首。武器技能减少 [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color]疲劳度积累。\n\n‘捅刺’、‘穿刺’和‘绝杀’减少1点行动点消耗，以允许每回合进行一次额外的攻击。",
	SpecSword = "精通剑术与利用对手的失误。武器技能减少[color=" + this.Const.UI.Color.NegativeValue + "]25%[/color]疲劳度积累。\n\n‘还击’不再有命中惩罚。\n\n‘致伤’造成伤势的阈值降低至[color=" + this.Const.UI.Color.NegativeValue + "]50%[/color]。\n\n‘竖劈’和‘横挥’的命中不再受到惩罚并提高[color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color]。",
	SpecSpear = "精通长矛与阻止敌人靠近。武器技能减少[color=" + this.Const.UI.Color.NegativeValue + "]25%[/color]疲劳度积累。\n\n‘矛墙’不再因控制区域内有敌人而失效，相反依旧可以使用并会继续自动攻击其它尝试进入控制区域的敌人。\n\n三尖叉和战叉攻击近身敌人不再有命中惩罚。",
	SpecPolearm = "精通长柄武器和与敌人保持距离。武器技能减少[color=" + this.Const.UI.Color.NegativeValue + "]25%[/color]疲劳度积累。\n\n长柄武器技能的行动点消耗减少到[color=" + this.Const.UI.Color.NegativeValue + "]5[/color]，并且攻击近身敌人不再有命中惩罚。",
	SpecHammer = "精通战锤和对付重装敌人。武器技能减少[color=" + this.Const.UI.Color.NegativeValue + "]25%[/color]疲劳度积累。\n\n‘毁甲’和‘拆甲’对护甲造成的伤害提高[color=" + this.Const.UI.Color.PositiveValue + "]33%[/color]\n\n‘击碎’的命中率提高[color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color]。\n\n长锤攻击近身敌人不再有命中惩罚。",
	SpecMace = "精通棍棒，不管对手穿没穿盔甲，使劲揍就完事。武器技能减少[color=" + this.Const.UI.Color.NegativeValue + "]25%[/color]疲劳度积累。\n\n‘打晕’，‘击翻’和‘击倒’将有[color=" + this.Const.UI.Color.PositiveValue + "]100%[/color]几率击晕不免疫击晕的敌人。\n\n长棒攻击近身敌人不再有命中惩罚。",
	SpecFlail = "精通链枷及绕过对手盾牌进行攻击。武器技能减少[color=" + this.Const.UI.Color.NegativeValue + "]25%[/color]疲劳度积累。\n\n‘抽打’和‘冰雹击’忽视盾牌的防御加成。\n\n‘砸击’在击中头部时额外忽略[color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color]护甲。\n\n‘回旋’的命中率提高[color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color]。"
};
gt.Const.Strings.Tooltip <- {
	World = {
		Hint_FocusParty = "点击聚焦队伍",
		Hint_FocusLocation = "点击聚焦位置"
	},
	Tactical = {
		Hint_FocusCharacter = "点击聚焦角色",
		Hint_CannotChangeItemInCombat = "无法在战斗中更改",
		Hint_OnlyActiveCharacterCanChangeItemsInCombat = "只有现在轮到的角色才能更换物品"
	}
};

